function [fitnessMatrix, preyFitnesses, predatorFitnesses] = UpdateFitnesses(fitnessMatrix, ...
                              preyPopulation, nPreyAgents, nPreyNeighbors, maxPreyTurningAngle, ...
                              nPreyNNInputs, nPreyNNHidden, nPreyNNOutputs, ...
                              predatorPopulation, nPredatorAgents, nPredatorNeighbors, maxPredatorTurningAngle, predatorSpeed, ...
                              nPredatorNNInputs, nPredatorNNHidden, nPredatorNNOutputs, ...
                              deltaT, maxTime, fieldSize, captureDistance, nCompetitions)
% run a number of simulations to fill in the missing fitnesses in our
% fitnessMatrix

[rows, cols] = find(~fitnessMatrix); % selects all (i,j) where fitnessMatrix(i,j)==0
for i = 1:length(rows)
    row = rows(i);
    col = cols(i);
    fitness = 0;
    for n = 1:nCompetitions
        thisFitness = Compete(preyPopulation(row,:), ...
                              nPreyAgents, nPreyNeighbors, maxPreyTurningAngle, ...
                              nPreyNNInputs, nPreyNNHidden, nPreyNNOutputs, ...
                              predatorPopulation(col,:), ...
                              nPredatorAgents, nPredatorNeighbors, maxPredatorTurningAngle, predatorSpeed, ...
                              nPredatorNNInputs, nPredatorNNHidden, nPredatorNNOutputs, ...
                              deltaT, maxTime, fieldSize, captureDistance);
        fitness = fitness + thisFitness;
    end
    fitnessMatrix(row,col) = fitness/nCompetitions;
end

preyFitnesses = sum(fitnessMatrix, 2)';
predatorFitnesses = -sum(fitnessMatrix, 1);